### ISSUE TITLE
Custom Error improvement

### ISSUE THREAD

**Issue by inf3rno** [inf3rno/dataflower#30]
I'll check `NativeError.apply(this, arguments)` in the `init()` of `Error`. I almost forgot I have that option. With that it may be (10% chance) possible to forget stack slicing manually and stack related compatibility issues.

I guess it won't work, but in that case I have to write custom Error integration code to the popular browsers. I think I'll cut the framework into multiple files: 1. inheritance, 2. custom errors, 3. pub/sub, 4. model-view, 5. ddd, 6. testing, and so on... In this case I'll need a plugin solution. 1+2+3 should be the core I think, the others are just sugar.

**Comment by inf3rno** [comment]
```js
function MyError() {
    var tmp = Error.apply(this, arguments);
    tmp.name = this.name = 'MyError'

    this.message = tmp.message
    /*this.stack = */Object.defineProperty(this, 'stack', { // getter for more optimizy goodness
        get: function() {
            return tmp.stack
        }
    })

    return this
}
```

Defining a property getter instead of debug mode would be much better...

**Comment by inf3rno** [comment]
```js
    Error.stackTraceLimit = 0; // disables it
    Error.stackTraceLimit = Infinity; // disables any limit
```

Change stack trace limit by V8.
http://www.devthought.com/2011/12/22/a-string-is-not-an-error/

**Comment by inf3rno** [comment]
https://github.com/stacktracejs/stacktrace.js for stacktrace generation.

**Comment by inf3rno** [comment]
`stacktrace` in Opera

**Comment by inf3rno** [comment]
partial stack for ie: http://www.eriwen.com/javascript/js-stack-trace/ (6y old)

**Comment by inf3rno** [comment]
A stack trace is typically exposed via the stack property of a thrown Exception. Newer browsers have more detailed exceptions, but they can be too detailed at times. Here is an example of a function that crashes and and prints a stack trace for the caught exception.
```js
function oops() {
  (function(a) {
    try {
      a.undefined();
    } catch (ex) {
      console.log(ex.stack)
    }
  })(null);
}
```
Running the code in Chrome, Opera or IE 10+ gives the following stack trace:
```
TypeError: Cannot read property 'undefined' of null
    at file:///Users/kyrylosilin/crashy.html:13:8
    at oops (file:///Users/kyrylosilin/crashy.html:17:9)
    at file:///Users/kyrylosilin/crashy.html:19:1
```
But in Firefox, or Safari, you get:
```
"oops/<@file:///Users/kyrylosilin/crashy.html:13:7
oops@file:///Users/kyrylosilin/crashy.html:17:1
@file:///Users/kyrylosilin/crashy.html:19:1
"
```
https://bugsnag.com/blog/javascript-notifier-upgrade

**Comment by inf3rno** [comment]
> Browser support: All browsers except older versions of IE provide a stack trace if you have an error object. In IE <10, it is simply impossible to get stack traces in Internet Explorer, using any method at all. 

https://errorception.com/docs/stacktraces

**Comment by inf3rno** [comment]
According to this: http://blog.meldium.com/home/2013/9/30/so-youre-thinking-of-tracking-your-js-errors by CORS you will get `ScriptError`, but that does not concern me.

**Comment by inf3rno** [comment]
http://docs.closure-library.googlecode.com/git/local_closure_goog_testing_stacktrace.js.source.html this code could be useful as well, but it is from 2009... :-)

**Comment by inf3rno** [comment]
> In IE <9, window.onerror is called with the function call stack intact. This means we can use arguments.callee.caller recursively to build up a fake stacktrace. It only gives us function names, not line numbers, but it's much better than nothing.

```js
// IE <9
window.onerror = function (message, file, line, column) {
    var column = column || (window.event && window.event.errorCharacter);
    var stack = [];
    var f = arguments.callee.caller;
    while (f) {
        stack.push(f.name);
        f = f.caller;
    }
    console.log(message, "from", stack);
}
```
https://bugsnag.com/blog/js-stacktraces/ from 2014

**Comment by inf3rno** [comment]
At least I know that the proper naming is `frame` and not `row` :-)

**Comment by inf3rno** [comment]
In V8 we can set the trace length. Now this is interesting, because by subclasses we need a longer trace length than usual, because of the many removed frames. So we might need to create multiple Error classes to count the proper trace length... By IE9- we can traick with arguments.callee.caller to get a partial stack trace, but without the filenames and lines I don't think it does worth the effort.

**Comment by inf3rno** [comment]
I think I'll support Chrome, Firefox, IE10+, maybe Opera and some mobile browser, which has stack support. I won't play with arguments.callee, unless somebody needs support for IE9-. I might add a factory, which will be extendable with this feature, so people will be able write a custom factory entry, for IE9. What I really need is a factory class. I need the same by X.instance() as well, so I'll add a new issue about this.

**Comment by inf3rno** [comment]
```js
var err = NativeError.call(this);
console.log(err.stack);
```
does not differ from
```js
var stack = new NativeError().stack;
console.log(stack);
```
you still need to remove the noise of unwanted frames...

**Comment by inf3rno** [comment]
http://www.codedependant.net/2015/01/24/better-errors-through-javascrip-inheritance/
additional properties: name, message, code, type

**Comment by inf3rno** [comment]
Most of the current browsers support Object.defineProperty as well: http://kangax.github.io/compat-table/es5/
So I'll remove the debug mode, and use that instead of.

**Comment by inf3rno** [comment]
I have to convert Firefox stack style into V8 stack style...

**Comment by inf3rno** [comment]
I think that's all I can find in the topic...

**Comment by inf3rno** [comment]
I cannot do anything about stack generation until I have no extendable factories.

**Comment by inf3rno** [comment]
How should a stack frame look like?

According to https://github.com/stacktracejs/stackframe/blob/master/stackframe.js it should be something like this:
```js
function _isNumber(n) {
    return !isNaN(parseFloat(n)) && isFinite(n);
}
function StackFrame(functionName, args, fileName, lineNumber, columnNumber) {
    if (functionName !== undefined) {
        this.setFunctionName(functionName);
    }
    if (args !== undefined) {
        this.setArgs(args);
    }
    if (fileName !== undefined) {
        this.setFileName(fileName);
    }
    if (lineNumber !== undefined) {
        this.setLineNumber(lineNumber);
    }
    if (columnNumber !== undefined) {
        this.setColumnNumber(columnNumber);
    }
}
StackFrame.prototype = {
    getFunctionName: function () {
        return this.functionName;
    },
    setFunctionName: function (v) {
        this.functionName = String(v);
    },
    getArgs: function () {
        return this.args;
    },
    setArgs: function (v) {
        if (Object.prototype.toString.call(v) !== '[object Array]') {
            throw new TypeError('Args must be an Array');
        }
        this.args = v;
    },
// NOTE: Property name may be misleading as it includes the path,
// but it somewhat mirrors V8's JavaScriptStackTraceApi
// https://code.google.com/p/v8/wiki/JavaScriptStackTraceApi and Gecko's
// http://mxr.mozilla.org/mozilla-central/source/xpcom/base/nsIException.idl#14
    getFileName: function () {
        return this.fileName;
    },
    setFileName: function (v) {
        this.fileName = String(v);
    },
    getLineNumber: function () {
        return this.lineNumber;
    },
    setLineNumber: function (v) {
        if (!_isNumber(v)) {
            throw new TypeError('Line Number must be a Number');
        }
        this.lineNumber = Number(v);
    },
    getColumnNumber: function () {
        return this.columnNumber;
    },
    setColumnNumber: function (v) {
        if (!_isNumber(v)) {
            throw new TypeError('Column Number must be a Number');
        }
        this.columnNumber = Number(v);
    },
    toString: function () {
        var functionName = this.getFunctionName() || '{anonymous}';
        var args = '(' + (this.getArgs() || []).join(',') + ')';
        var fileName = this.getFileName() ? ('@' + this.getFileName()) : '';
        var lineNumber = _isNumber(this.getLineNumber()) ? (':' + this.getLineNumber()) : '';
        var columnNumber = _isNumber(this.getColumnNumber()) ? (':' + this.getColumnNumber()) : '';
        return functionName + args + fileName + lineNumber + columnNumber;
    }
};

```

**Comment by inf3rno** [comment]
`functionName, args, fileName, lineNumber, columnNumber`
Now what I don't care is functionName + args, so they can be merged into a description.
They fileName will be path by me. The lineNumber will be row, the columnNumber will be col. That's all, short and clean.

**Comment by inf3rno** [comment]
There are example stacks here: https://github.com/stacktracejs/error-stack-parser/blob/master/spec/fixtures/captured-errors.js
So it is possible to write different factories with different parsers...

**Comment by inf3rno** [comment]
I decided not to add other error plugin. V8 is enough until I want to test things in the browser. Maybe later it will be necessary to display browser related errors in a proper form. I don't think it does worth the effort, but we will see when I start browser tests...

**Comment by inf3rno** [comment]
By Composite Errors like Plugin.Incompatible(err) we have to do something like this:

```js
var message = "InCompatible: incompatible plugin <"+err.name+err.message+">";
var stack = [
  "new Incompatible (plugin.js:1000:1) ",
  "new TypeError (plugin.js:123:5)",
  "..."
].join("\n")
```

**Comment by inf3rno** [comment]
Hmm I don't think there is a general approach for Composite Errors... Their message should be Composite, their stack can vary... The biggest problem is with merging the stack of more than 2 Errors... Afaik there is no support for something like that... Hmm I'll try...

A java composite stack from here: https://community.oracle.com/thread/2176201
```js
<Feb 11, 2011 9:39:49 AM IST> <Error> <ServletContext-/soa-infra> <BEA-000000> <
Error during deployment
oracle.fabric.common.FabricException: Deployment Failed: java.lang.SecurityExcep
tion: [Security:090398]Invalid Subject: weblogic: [Security:090398]Invalid Subje
ct: weblogic
at oracle.integration.platform.blocks.deploy.StandaloneCompositeDeployme
ntCoordinatorImpl.coordinateCompositeDeployment(StandaloneCompositeDeploymentCoo
rdinatorImpl.java:37)
at oracle.integration.platform.blocks.deploy.servlet.BaseDeployProcessor
.deployNewComposite(BaseDeployProcessor.java:359)
at oracle.integration.platform.blocks.deploy.servlet.BaseDeployProcessor
.deploySARs(BaseDeployProcessor.java:219)
at oracle.integration.platform.blocks.deploy.servlet.DeployProcessor.doD
eployWork(DeployProcessor.java:161)
at oracle.integration.platform.blocks.deploy.servlet.DeployProcessor.doD
eployWork(DeployProcessor.java:110)
Truncated. see log file for complete stacktrace

Caused By: oracle.fabric.common.FabricDeploymentException: java.lang.SecurityExc
eption: [Security:090398]Invalid Subject: weblogic: [Security:090398]Invalid Sub
ject: weblogic {rootCauses=[]}
at oracle.integration.platform.blocks.deploy.CommonDeploymentManager.log
Error(CommonDeploymentManager.java:90)
at oracle.integration.platform.blocks.deploy.CompositeDeploymentManagerI
mpl.initDeployment(CompositeDeploymentManagerImpl.java:150)
at oracle.integration.platform.blocks.deploy.CompositeDeploymentManagerI
mpl.load(CompositeDeploymentManagerImpl.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
Truncated. see log file for complete stacktrace

Caused By: java.lang.SecurityException: [Security:090398]Invalid Subject: weblog
ic
at weblogic.rjvm.ResponseImpl.unmarshalReturn(ResponseImpl.java:234)
at weblogic.rmi.cluster.ClusterableRemoteRef.invoke(ClusterableRemoteRef
.java:348)
at weblogic.rmi.cluster.ClusterableRemoteRef.invoke(ClusterableRemoteRef
.java:259)
at weblogic.jndi.internal.ServerNamingNode_1033_WLStub.lookup(Unknown So
urce)
at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:405)
Truncated. see log file for complete stacktrace

Caused By: java.lang.SecurityException: [Security:090398]Invalid Subject: weblog
ic
at weblogic.security.service.SecurityServiceManager.seal(SecurityService
Manager.java:698)
at weblogic.rjvm.MsgAbbrevInputStream.getSubject(MsgAbbrevInputStream.ja
va:205)
at weblogic.rmi.internal.BasicServerRef.acceptRequest(BasicServerRef.jav
a:841)
at weblogic.rmi.internal.BasicServerRef.dispatch(BasicServerRef.java:307
)
at weblogic.rjvm.RJVMImpl.dispatchRequest(RJVMImpl.java:1114)
Truncated. see log file for complete stacktrace
>
<Feb 11, 2011 9:39:49 AM IST> <Error> <oracle.integration.platform.blocks.deploy
.servlet> <SOA-21037> <Sending back error message: Error during deployment: Depl
oyment Failed: java.lang.SecurityException: [Security:090398]Invalid Subject: we
blogic: [Security:090398]Invalid Subject: weblogic..>
Received HTTP response from the server, response code=500 
```

**Comment by inf3rno** [comment]
So the "caused by" is the proper term I guess... It is interesting... how to add this info to the stack and stay stack parser compatible????

I don't know yet... I transform every stack to v8 style... But I don't think v8 stack supports such a feature...

There is a fine java code here about Composite Error implementation: https://dev.vaadin.com/svn/versions/6.8/src/com/vaadin/terminal/CompositeErrorMessage.java

**Comment by inf3rno** [comment]
I asked the question here http://stackoverflow.com/questions/28491667/javascript-v8-composite-error-stack-format
Maybe somebody has a great idea about stack merging...

**Comment by inf3rno** [comment]
> The stack property is set to undefined when the error is constructed, and gets the trace information when the error is raised. If an error is raised multiple times, the stack property is updated each time the error is raised.

https://msdn.microsoft.com/en-us/library/ie/hh699850%28v=vs.94%29.aspx

**Comment by inf3rno** [comment]
By MSIE the stack is generated only by throwing, so I have to use something like this:

```js
var Error = extend(NativeError, {
	id: undefined,
	name: "Error",
	message: "",
	configure: Object.prototype.configure,
	isOptions: Object.prototype.isOptions,
	init: function (options, preprocessor) {
		this.id = id();
		if (typeof (options) == "string")
			options = {message: options};
		this.configure(options, preprocessor);

		var nativeError;
		try {
			throw new NativeError();
		} catch (coughtError){
			nativeError = coughtError;
		}
		
		var error = this;
		var stack;
		NativeObject.defineProperty(this, "stack", {
			enumerable: true,
			get: function () {
				if (stack === undefined) {
					stack = "";
					stack += error.name + " " + error.message + "\n";
					stack += Stack.instance(nativeError);
					delete(nativeError);
				}
				return stack;
			}
		});
	}
}, {
	instance: Object.instance,
	extend: Object.extend
});
```

**Comment by inf3rno** [comment]
Ez nyilván nem hat ki a natív error osztályokra, úgyhogy ha azokból akarnak kompozitot összerakni, akkor előtte mindenképp el kell dobni őket (legalábbis msie-nél)

Át kell terveznem a Container + Factory témát teljes mértékben... Az error-hoz mindenképp egy Container kell egy lista StackParserrel, amik nem Factory-k... ezek kapnak egy Stack példányt, és azt próbálják feltölteni. Mindengyiknek lesz egy compatible() függvénye, ami megmondja, hogy az adott stack-el kompatibilis-e. Mondjuk már a hozzáadásnál is csekkolhatjuk egy tetszőleges error példányosításánál, hogy minden rendben van e, de ott jelenleg csak azt csekkolom, hogy nem e dob errort parsolás közben... Én ahelyett inkább a formátumra jellemző regex-et adnék mindegyiknek, és az parsolna, aminél először egyezik a regex. Ami izgalmas még itt, hogy meg lehetne csinálni úgy a rendszert, hogy súlyozás alapján menne a bejárás. Tehát ha az egyik parser sok error-t fel tudott dolgozni, akkor a lista elejére tesszük és így menet közben optimalizál a kereső. Ez megint egy új gyűjtemény típus lenne...

**Comment by inf3rno** [comment]
Composite error with stack format compatible solution:

```js
var stackString = [
    "CompositeError msg - composed of #aaa:Error msg1 #bbb:TypeError msg2 #ccc:Error msg3",
    "   at module.exports.extend.init (http://example.com/example.js:75:31)",
    "   at new Descendant (http://example.com/example.js:11:27)",
    "   at Error (#aaa:0:0)",
    "   at custom (http://example.com/spec/example.spec.js:222:23)",
    "   at Object.<anonymous> (http://example.com/spec/example.spec.js:224:13)",
    "   at TypeError (#bbb:0:0)",
    "   at http://example.com/spec/example.spec.js:10:20",
    ...
].join("\n");
```

**Comment by inf3rno** [comment]
Now this is a good approach, but what about nested composites?

```
Composite a
- x: Composite b
-- y: TypeError c
-- z: Error d
- q: Error: e
```

```
Composite a of #x Composite b #x.y TypeError c #x.z Error d #q Error e
 at ...
 at new Composite (#x:0:0)
 at ...
 at new TypeError (#x.y:0:0)
 at ...
 at new Error (#x.z:0:0)
 at ...
 at new Error (#q:0:0)
 at ...
```

I think this is perfect...

Now how to implement it?

```
flat = Composite.flat() -> {"x": this.x, "x.y": this.x.y, "x.z": this.x.z, "q": this.q}
each flat as path:err
    message.push("#{path} {err.name} {err.message}")
    stackString.push(" at new {err.name}(#{path}:0:0)")
    stackString.push(err.stackString)
```

So it is possible to do all of these in the Composite.toString() or somewhere there...

**Comment by inf3rno** [comment]
I think Stack and Frame should be string injectable, so if a parser cannot parse the string, it can have still limited functionality... Or I can define RawStack and probably RawFrame...

I can have special Composites for example by validation I should be able to Composite.add(err) without any issue. Ofc. I could do something like new Composite([err1, err2]) etc... in which I don't need add... So Composites should be able to use collections like arrays and hashsets.

**Comment by inf3rno** [comment]
I have to redesign somehow Stack instantiation... The current Stack.instance(nativeError) is not good enough to me... I don't need Factories... I can instantiate the Stack with new Stack() and after that I can send it to parsers which fill them with details... The Factory is only to increase the decoupling from the Stack class. So with Factory I can use Stack relatives too...

I think Error.stack should store a Stack instance so if I want to use it for logging purposes it will be nice... By String(Error.stack) I'll have a slight problem if the stack does not know the CompositeError, because in that case it cannot push() the stacks of the participant Errors...

**Comment by inf3rno** [comment]
This Stack instantiation problem will be solved by replacing the Container + Factory solution with Wrapper. #33

**Comment by inf3rno** [comment]
I replaced it with a Wrapper using `firstMatchCascade` algorithm. It's nice. Maybe slower than the original, but who cares... The metrics will decide this, not me...

**Comment by inf3rno** [comment]
I reduces the code to preprocessors. The current one calls `StackParser.parse(options{string}) -> options{frames}`. Perfect.

**Comment by inf3rno** [comment]
I'll need message template support or at least message callback function support.

```js
var TimerError = UserError.extend({
    message: "Failed at {d.hours}:{d.mins}"
});
new TimerError({d: new Date()})
```

I think I don't want to use templates.... I'd rather stay with callbacks functions. Much easier to implement...

```js
var TimerError = UserError.extend({
    message: function (){
        return "Failed at "+moment(new Date(), "MM-DD-YYYY");
    }
});
new TimerError({d: new Date()})
```
http://momentjs.com/docs/

**Comment by inf3rno** [comment]
Okay, tomorrow I'll implement Composite Errors once and for all...

**Comment by inf3rno** [comment]
I have to refactor the current Stack creation code if I want composite stacks. Currently this.stack returns only a string, which is unacceptable. I think it should return a Stack object. The v8 stack creation is poorly defined, because by v8 API it is possible to get a stack array. I think I should use the same stack array approach instead of Stack and Frame classes.

**Comment by inf3rno** [comment]
So before CompositeError implementation I have to give an answer to this issues.

**Comment by inf3rno** [comment]
The current Stack creation code:

```js
    createStack: function (options) {
        return new Stack(options);
    }
```

**Comment by inf3rno** [comment]
The new Error format is:

```js
var stackString = [
    "CompositeError msg",
    "   at custom (http://example.com/spec/example.spec.js:222:23)",
    "   at Object.<anonymous> (http://example.com/spec/example.spec.js:224:13)",
    "UserError a msga",
    "   at custom (http://example.com/spec/example.spec.js:222:23)",
    "   at Object.<anonymous> (http://example.com/spec/example.spec.js:224:13)",
    "CompositeError b msgb",
    "   at custom (http://example.com/spec/example.spec.js:222:23)",
    "   at Object.<anonymous> (http://example.com/spec/example.spec.js:224:13)",
    "UserError b.x msgx",
    "   at custom (http://example.com/spec/example.spec.js:222:23)",
    "   at Object.<anonymous> (http://example.com/spec/example.spec.js:224:13)",
    ...
].join("\n");
```

It currently supports UserError only. I'll think about native Error support, but I don't want to inject the property name into them... :S

**Comment by inf3rno** [comment]
I don't care about Stack parser compatibility anymore. I'll probably add logger adapters by integration. #18

**Comment by inf3rno** [comment]
I rethink the template to support native errors.

```js
    "UserError b.x msgx",
    "   at custom (http://example.com/spec/example.spec.js:222:23)",
    "   at Object.<anonymous> (http://example.com/spec/example.spec.js:224:13)",
    ...
```

hmmm maybe this will suffice:

```js
    "caused by <b.x> UserError msgx",
    "   at custom (http://example.com/spec/example.spec.js:222:23)",
    "   at Object.<anonymous> (http://example.com/spec/example.spec.js:224:13)",
    ...
```

yepp this will be what I'll use.
