### ISSUE TITLE
WeightedSet

### ISSUE THREAD

**Issue by inf3rno** [inf3rno/dataflower#41]
By #30 we defined a new Collection type.

The feature what it know is weighting the items. E.g.:

```js
var filter = "..";
coll.find(function (item){
    return item.regex.test(filter);
});
```

This is a simple search, but after finding the right item, it increases its weight.

e.g.

```js
{
    items: [a,b,c,d],
    weights: [0,0,0,0]
}
```
after finding c:

```js
{
    items: [a,b,c,d],
    weights: [0,0,1,0]
}
```
or
```js
{
    items: [c,a,b,d],
    weights: [1,0,0,0]
}
```

So next time c will be the first item, and finding it will be much faster...
Alternative ways:

```js
{
    items: [a,b,c,d],
    weights: [[2,1],[0,0],[1,0],[3,0]]
}

{
    items: {
        1: [c],
        0: [a,b,d]
    }
}

{
    items: [a,b,c,d],
    weights: {
        1: [2],
        0: [0,1,3]
    }
}
```

I prefer the last one, but we won't be able to iterate it this way:

```js
for (index in coll.items)
```

just this way:

```js
var arr = coll.toArray();
for (index in arr)
```

**Comment by inf3rno** [comment]
Another alternative way to use hashsets:
```js
{
    items: {
        1: {id3:c},
        0: {id1:a, id2:b, id3:c}
    }
}
```
I think this is the best so far...

If we add
```
var id;
NativeObject.defineProperty(this, "id", {getter: function (){if (!id) id = id(); return id;}});
```

to Object.prototype, then we don't have to generate id by every Object instance, but we will be able to get the id if we need it. I don't know which is faster, adding id generation to the init(), or running this property definition in the init... Maybe the first one is the better approach, so every instance should have an id from the beginning...

**Comment by inf3rno** [comment]
I'll define this type of collection only for HashSets...

**Comment by inf3rno** [comment]
Composite error with stack format compatible soltion:

```js
var stackString = [
    "CompositeError msg - composed of #aaa:Error msg1 #bbb:TypeError msg2 #ccc:Error msg3",
    "   at module.exports.extend.init (http://example.com/example.js:75:31)",
    "   at new Descendant (http://example.com/example.js:11:27)",
    "   at Error (#aaa:0:0)",
    "   at custom (http://example.com/spec/example.spec.js:222:23)",
    "   at Object.<anonymous> (http://example.com/spec/example.spec.js:224:13)",
    "   at TypeError (#bbb:0:0)",
    "   at http://example.com/spec/example.spec.js:10:20",
    ...
].join("\n");
```

**Comment by inf3rno** [comment]
Now this is a good approach, but what about nested composites?

```
Composite a
- x: Composite b
-- y: TypeError c
-- z: Error d
- q: Error: e
```

```
Composite a of #x Composite b #x.y TypeError c #x.z Error d #q Error e
 at ...
 at new Composite (#x:0:0)
 at ...
 at new TypeError (#x.y:0:0)
 at ...
 at new Error (#x.z:0:0)
 at ...
 at new Error (#q:0:0)
 at ...
```

I think this is perfect...

Now how to implement it?

```
flat = Composite.flat() -> {"": this, "x": this.x, "x.y": this.x.y, "x.z": this.x.z, "q": this.q}
each flat as path:err
    stackString.push(err.stackString)
    message.push("#{path} {err.name} {err.message}")
```

**Comment by inf3rno** [comment]
I think Stack and Frame should be string injectable, so if a parser cannot parse the string, it can have still limited functionality... Or I can define RawStack and probably RawFrame...

**Comment by inf3rno** [comment]
I can have special Composites for example by validation I should be able to Composite.add(err) without any issue. Ofc. I could do something like new Composite([err1, err2]) etc... in which I don't need add... So Composites should be able to use collections like arrays and hashsets.

**Comment by inf3rno** [comment]
This might be needed in Fluent, but I guess I won't implement it.

**Comment by inf3rno** [comment]
I would never need it.
